### ISSUE TITLE
How can i add a password ?

### ISSUE THREAD

**Issue by SciammarellaB** [9paradox/nuget-package-source#3]
I'm using a source that has password to use and I can't find anywhere to set this password.
How can i set the password for the source ?

**Comment by 9paradox** [comment]
Hi @SciammarellaB 
Currently this extension doesn't support adding username and password while creating a new nuget source. I will try to add this feature. For now you can add it manually by running [dotnet command](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source) :
`dotnet nuget add source https://someServer/myTeam -n mySource -u myUsername -p myPassword`

**Comment by SciammarellaB** [comment]
Thanks mate.
I didn't knew about this command.
I'm new programming .NET in VSCode and still lost in how doing things without the tools that Visual Studio has.
