### ISSUE TITLE
Using option --store-password-in-clear-text

### ISSUE THREAD

**Issue by SciammarellaB** [9paradox/nuget-package-source#4]
Hi, thank you for the update adding user and passowrd that i asked some days ago.
I had other issue related with the type of password that i user that is kind of a key / hash code.
When you told about the command "dotnet nuget add", i took a look and used it with no problem exccept this config called 
"--store-password-in-clear-text".
I needed to configure other machine at work today and saw your update but couldn't find this option.

**Comment by 9paradox** [comment]
Hi, 
I have added support for "--store-password-in-clear-text" flag while adding or update a package source.
The v0.3.0 should be up soon.
